// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/Popolzen/shortener/internal/repository (interfaces: URLRepository)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_repository.go -package=mocks github.com/Popolzen/shortener/internal/repository URLRepository
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	model "github.com/Popolzen/shortener/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockURLRepository is a mock of URLRepository interface.
type MockURLRepository struct {
	ctrl     *gomock.Controller
	recorder *MockURLRepositoryMockRecorder
	isgomock struct{}
}

// MockURLRepositoryMockRecorder is the mock recorder for MockURLRepository.
type MockURLRepositoryMockRecorder struct {
	mock *MockURLRepository
}

// NewMockURLRepository creates a new mock instance.
func NewMockURLRepository(ctrl *gomock.Controller) *MockURLRepository {
	mock := &MockURLRepository{ctrl: ctrl}
	mock.recorder = &MockURLRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockURLRepository) EXPECT() *MockURLRepositoryMockRecorder {
	return m.recorder
}

// DeleteURLs mocks base method.
func (m *MockURLRepository) DeleteURLs(userID string, urlIDs []string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "DeleteURLs", userID, urlIDs)
}

// DeleteURLs indicates an expected call of DeleteURLs.
func (mr *MockURLRepositoryMockRecorder) DeleteURLs(userID, urlIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteURLs", reflect.TypeOf((*MockURLRepository)(nil).DeleteURLs), userID, urlIDs)
}

// Get mocks base method.
func (m *MockURLRepository) Get(shortURL string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", shortURL)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockURLRepositoryMockRecorder) Get(shortURL any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockURLRepository)(nil).Get), shortURL)
}

// GetUserURLs mocks base method.
func (m *MockURLRepository) GetUserURLs(userID string) ([]model.URLPair, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserURLs", userID)
	ret0, _ := ret[0].([]model.URLPair)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserURLs indicates an expected call of GetUserURLs.
func (mr *MockURLRepositoryMockRecorder) GetUserURLs(userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserURLs", reflect.TypeOf((*MockURLRepository)(nil).GetUserURLs), userID)
}

// Store mocks base method.
func (m *MockURLRepository) Store(shortURL, longURL, userID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Store", shortURL, longURL, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Store indicates an expected call of Store.
func (mr *MockURLRepositoryMockRecorder) Store(shortURL, longURL, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Store", reflect.TypeOf((*MockURLRepository)(nil).Store), shortURL, longURL, userID)
}
